### ISSUE TITLE
Testing the Framework

### ISSUE THREAD

**Issue by Senaxx** [aFreshMelon/destiny-php#2]
I downloaded your scripts, but i'm wondering, could you include a working example for extracting info? I saw your "tests" folder, but bootstrap.php had an include

$loader = require __DIR__ . "/../vendor/autoload.php";

and this is not included in your api? Or am I just simply missing something?

**Comment by aFreshMelon** [comment]
Tests are working as they should. You can see results on [Travis CI](https://travis-ci.org/aFreshMelon/destiny-php).

**Comment by aFreshMelon** [comment]
I've removed the tests for now as they were quite bad and not efficient.
