### ISSUE TITLE
Composer failure

### ISSUE THREAD

**Issue by brucethehoon** [aFreshMelon/destiny-php#3]
I'm getting the following message when attempting to install.  I'd appreciate any assistance you could provide!

C:\xampp\htdocs\dest>composer require afreshmelon/destiny dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package afreshmelon/destiny 1.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

C:\xampp\htdocs\dest>

**Comment by aFreshMelon** [comment]
[It seems I can't reproduce this...](http://i.imgur.com/Fg7hZ5w.png)

That said, I do not know why it is looking for version 1.0.0 for you since you are stating the branch as dev-master and specifically not version 1.0.0 since it's not available. I assume this is a Windows related issue. I will try to fix this.

**Comment by aFreshMelon** [comment]
As a workaround you can now pull the latest release version using ``composer require afreshmelon/destiny`` without the dev-master. This won't give you the latest code, but it should mostly be up to date. It's only a workaround.
