### ISSUE TITLE
How to add API Key

### ISSUE THREAD

**Issue by Costellos** [aFreshMelon/destiny-php#5]
Per Bungie Documentation the API key is required, any way to make it so that we can add our own API key? 

Thanks,
Steven C

**Comment by aFreshMelon** [comment]
There is no need for any sort of API key, this wrapper uses public endpoints.

**Comment by Costellos** [comment]
I know right now they aren't required for public endpoints, but they even say that that might change how its done in the future, and if they do, wont any apps built on this break?

**Comment by aFreshMelon** [comment]
Yes, but as of now their API endpoints don't even accept a key so I can't implement it.

**Comment by Costellos** [comment]
Ahh ok. Just making sure. Thanks
