### ISSUE TITLE
Help with Grimoire and Active Bounsues

### ISSUE THREAD

**Issue by Costellos** [aFreshMelon/destiny-php#6]
How to access the Grimoire Cards themselves and the active bounces that come with completing them?

I'm sure it has to do with fetchGrimoireData(); but I'm not 100% sure how to access half of the data in that object.

Thanks,
Steve C

**Comment by aFreshMelon** [comment]
As definitions are enabled for the Grimoire response you may use them to get detailed info about any card a player has. Just check the "cardDefinitions" key in the array returned by ``fetchGrimoireData``.
